# This is a basic workflow to help you get started with Actions


pm
# Controls when the action will run. Triggers the workflow on push or pull request
but only for the master branch
on:
  
    
  
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    

    # Runs a single command using the runners shell
     one-line script
      !

    # Runs a set of commands using the runners shell
    
      run: |
        
        
